trainer: energy

dataset:
  train:
    src: /home/a113/nyx/ocp-main/data/oc20_ni/train/data.lmdb
    normalize_labels: True
    target_mean: -1.525913953781128
    target_std: 2.279365062713623
  val:
    src: /home/a113/nyx/ocp-main/data/oc20_ni/val_id/data.lmdb
  test:
    src: /home/a113/nyx/ocp-main/data/oc20_ni/val_id/data.lmdb

logger: tensorboard

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
